### POST
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome" : "Matheus Leandro Ferreira",
  "telefone": "123",
  "dataNascimento": "1986-09-28",
  "matriculas": [
    {
      "codigoMatricula": "123",
      "nomeCurso": "Computacao",
      "dataInicio": "2025-06-15"
    }
  ]
}

### Listar todos os alunos...
GET http://localhost:8080/alunos

###

### Listar todos os alunos...
GET http://localhost:8080/alunos/1/matriculas